import Link from "next/link";
import { ActionNotice } from "@/components/action-notice";
import { FormStatusButton } from "@/components/form-status-button";
import { ScreenHeader } from "@/components/screen-header";
import { signOut } from "@/features/auth/actions";
import { documents } from "@/features/documents/catalog";
import { ResetUsageButton } from "@/features/settings/reset-usage-button";
import { updateSettings } from "@/features/settings/actions";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const { notice } = await searchParams; const supabase = await createSupabaseServerClient(); const { data } = await supabase.from("app_settings").select("key, value"); const values = Object.fromEntries((data ?? []).map((row: { key: string; value: unknown }) => [row.key, row.value]));
  return <main><ScreenHeader eyebrow="A tu manera" title="Ajustes" /><ActionNotice notice={notice} /><form action={updateSettings} className="mx-5 mt-5 space-y-5 sm:mx-7"><section className="rounded-[1.5rem] bg-white p-5 shadow-sm"><h2 className="font-black">Generador</h2><div className="mt-5 space-y-5"><label className="block text-sm font-bold">Modo<select className="mt-2 block min-h-12 w-full rounded-xl bg-[#fff8f0] px-3" defaultValue={String(values.variety_mode ?? "balanced")} name="mode"><option value="variety">Variedad</option><option value="balanced">Equilibrado</option><option value="practical">Práctico</option></select></label><label className="block text-sm font-bold">Semanas antes de repetir<input className="mt-2 block min-h-12 w-full rounded-xl bg-[#fff8f0] px-3" defaultValue={String(values.repeat_weeks ?? 4)} min="1" name="repeatWeeks" type="number"/></label><label className="block text-sm font-bold">Máximo de cenas con hidrato<input className="mt-2 block min-h-12 w-full rounded-xl bg-[#fff8f0] px-3" defaultValue={String(values.max_dinner_carbs ?? 2)} min="0" name="maxDinnerCarbs" type="number"/></label><label className="block text-sm font-bold">Alternativas por cambio<input className="mt-2 block min-h-12 w-full rounded-xl bg-[#fff8f0] px-3" defaultValue={String(values.alternative_count ?? 4)} max="5" min="3" name="alternatives" type="number"/></label></div></section><FormStatusButton className="min-h-13 w-full rounded-2xl bg-[#e85d4a] font-black text-white disabled:opacity-60" idle="Guardar ajustes" pending="Guardando ajustes..." /></form><section className="mx-5 mt-5 rounded-[1.5rem] bg-white p-5 shadow-sm sm:mx-7"><h2 className="font-black">Documentos de consulta</h2><p className="mt-2 text-sm leading-6 text-[#66716b]">Menús originales disponibles solo para consulta.</p><div className="mt-4 divide-y divide-stone-100">{documents.map((document) => <Link className="flex min-h-14 items-center justify-between gap-3 py-3 first:pt-0 last:pb-0" href={`/settings/documents/${document.id}`} key={document.id}><span><span className="block text-sm font-black">{document.title}</span><span className="mt-1 block text-xs font-medium text-[#66716b]">{document.date}</span></span><span className="rounded-xl bg-[#fff0eb] px-3 py-2 text-xs font-black text-[#e85d4a]">Ver PDF</span></Link>)}</div></section><section className="mx-5 mt-5 rounded-[1.5rem] bg-white p-5 shadow-sm sm:mx-7"><h2 className="font-black">Historial de uso</h2><p className="mt-2 text-sm leading-6 text-[#66716b]">Borra los eventos usados para el contador de platos. Tus menús no se modificarán.</p><div className="mt-4"><ResetUsageButton /></div></section><form action={signOut} className="mx-5 mt-7 pb-5 text-center sm:mx-7"><FormStatusButton className="min-h-11 text-sm font-bold text-[#66716b] disabled:opacity-60" idle="Cerrar sesión" pending="Cerrando sesión..." /></form></main>;
}
