import Link from "next/link";
import { ArrowDown, ArrowUp, History, Moon, Utensils } from "lucide-react";
import { ScreenHeader } from "@/components/screen-header";
import { MealStatusForm } from "@/features/meals/meal-status-form";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type MealsParams = { type?: "lunch" | "dinner"; status?: "active" | "inactive"; sort?: "asc" | "desc"; notice?: string };

export default async function MealsPage({ searchParams }: { searchParams: Promise<MealsParams> }) {
  const params = await searchParams; const type = params.type === "dinner" ? "dinner" : "lunch"; const inactive = params.status === "inactive"; const sort = params.sort === "asc" ? "asc" : "desc";
  const supabase = await createSupabaseServerClient(); const { data } = await supabase.from("meals").select("id, name").eq("meal_type", type).eq("active", !inactive).order("name"); const meals = (data ?? []) as Array<{ id: string; name: string }>;
  const ids = meals.map((meal) => meal.id); const { data: events } = ids.length ? await supabase.from("meal_usage_events").select("meal_id").in("meal_id", ids).in("event_type", ["generated", "selected", "replaced_in"]) : { data: [] };
  const usage = new Map<string, number>(); for (const event of events ?? []) usage.set(String(event.meal_id), (usage.get(String(event.meal_id)) ?? 0) + 1);
  meals.sort((left, right) => { const difference = (usage.get(left.id) ?? 0) - (usage.get(right.id) ?? 0); return difference === 0 ? left.name.localeCompare(right.name, "es") : sort === "asc" ? difference : -difference; });
  const href = (nextType = type, nextInactive = inactive, nextSort = sort) => `/meals?type=${nextType}${nextInactive ? "&status=inactive" : ""}&sort=${nextSort}`; const returnTo = href(); const label = type === "lunch" ? "Almuerzos" : "Cenas"; const MealIcon = type === "lunch" ? Utensils : Moon; const SortIcon = sort === "desc" ? ArrowDown : ArrowUp;
  return <main><ScreenHeader eyebrow="Tu recetario" title="Platos" /><div className="mx-5 mt-4 flex rounded-2xl bg-white p-1 shadow-sm sm:mx-7"><Link aria-current={type === "lunch" ? "page" : undefined} className={`flex min-h-11 flex-1 items-center justify-center rounded-xl text-sm font-black ${type === "lunch" ? "bg-[#f59e42] text-white" : "text-[#66716b]"}`} href={href("lunch")}>Almuerzos</Link><Link aria-current={type === "dinner" ? "page" : undefined} className={`flex min-h-11 flex-1 items-center justify-center rounded-xl text-sm font-black ${type === "dinner" ? "bg-[#1f9e9a] text-white" : "text-[#66716b]"}`} href={href("dinner")}>Cenas</Link></div><div className="mx-5 mt-4 flex items-center justify-between gap-3 sm:mx-7"><Link className={`min-h-10 rounded-xl px-3 py-2 text-xs font-black ${inactive ? "bg-[#24302b] text-white" : "bg-white text-[#66716b] shadow-sm"}`} href={href(type, !inactive)}>{inactive ? "Ver activos" : "Desactivados"}</Link><div className="flex items-center gap-2"><span className="text-[10px] font-black uppercase tracking-wider text-[#66716b]">Ordenar por</span><Link aria-label={sort === "desc" ? "Ordenar de menos a más" : "Ordenar de más a menos"} className="grid size-10 place-items-center rounded-xl bg-white shadow-sm" href={href(type, inactive, sort === "desc" ? "asc" : "desc")} title={sort === "desc" ? "Más usados primero" : "Menos usados primero"}><SortIcon aria-hidden="true" className="size-4" strokeWidth={2} /></Link></div></div><p className="mx-5 mt-3 text-xs font-bold text-[#66716b] sm:mx-7">{inactive ? `${label} desactivados` : `${label} activos`} · {sort === "desc" ? "más usados primero" : "menos usados primero"}</p><div className="mt-4 space-y-3 px-5 sm:px-7">{meals.map((meal) => { const count = usage.get(meal.id) ?? 0; return <article className={`flex items-center gap-3 rounded-2xl p-4 shadow-sm ${inactive ? "bg-stone-100 text-stone-500" : "bg-white"}`} key={meal.id}><MealIcon aria-hidden="true" className={`size-5 ${inactive ? "opacity-50" : ""}`} strokeWidth={2} /><div className="min-w-0 flex-1"><h2 className="truncate font-black">{meal.name}</h2><p className="mt-1 flex items-center gap-1 text-xs font-bold text-[#66716b]"><History aria-hidden="true" className="size-3.5" strokeWidth={2} />{count}</p></div><MealStatusForm active={!inactive} id={meal.id} name={meal.name} returnTo={returnTo} /></article>; })}{!meals.length && <section className="rounded-2xl bg-white p-6 text-center shadow-sm"><p className="font-black">No hay {inactive ? "platos desactivados" : `${label.toLowerCase()} activos`}.</p><p className="mt-2 text-sm text-[#66716b]">{inactive ? "Los platos que apagues aparecerán aquí." : "Activa un plato desde el filtro de desactivados."}</p></section>}</div></main>;
}
