import Link from "next/link";
import { Moon, RefreshCw, Utensils } from "lucide-react";
import { ScreenHeader } from "@/components/screen-header";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Ingredient = { name: string; quantity_laura: number | null; quantity_jesus: number | null; unit: string | null; quantity_note: string | null; quantity_text_laura: string | null; quantity_text_jesus: string | null; quantity_shared_text: string | null };
function quantity(text: string | null, value: number | null, note: string | null, unit: string | null, person: "laura" | "jesus") { if (text) return text; const pair = note?.split(/\s+\/\s+/).map((part) => part.trim()); if (pair?.length === 2) return person === "laura" ? pair[0]! : pair[1]!; return `${value ?? note ?? "Sin cantidad"}${unit ? ` ${unit}` : ""}`; }

export default async function TodayPage() {
  const now = new Date(); const day = now.getDay(); const monday = new Date(now); monday.setDate(now.getDate() - ((day + 6) % 7)); const weekStart = monday.toISOString().slice(0, 10); const today = now.toISOString().slice(0, 10); const supabase = await createSupabaseServerClient();
  const { data: menu } = await supabase.from("weekly_menus").select("weekly_menu_items(id, menu_date, meal_slot, meals!weekly_menu_items_meal_id_fkey(name, cooking_method, meal_ingredients(name, quantity_laura, quantity_jesus, unit, quantity_note, quantity_text_laura, quantity_text_jesus, quantity_shared_text)))").eq("week_start", weekStart).maybeSingle();
  const items = ((menu?.weekly_menu_items ?? []) as Array<Record<string, unknown>>).filter((item) => item.menu_date === today); const formatted = now.toLocaleDateString("es-ES", { weekday: "long", day: "numeric", month: "long", timeZone: "Europe/Madrid" }); const weekend = day === 0 || day === 6;
  return <main><ScreenHeader eyebrow={`Hoy, ${formatted}`} title={weekend ? "Día libre" : "A comer bien"} action={<Link aria-label="Ver semana" className="rounded-2xl bg-white px-4 py-3 text-sm font-bold text-[#24302b] shadow-sm" href="/week">Semana</Link>} />
    {weekend ? <section className="mx-5 mt-6 rounded-[1.75rem] bg-[#dff4ee] p-7 sm:mx-7"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#1f9e9a]">Tiempo para ti</p><h2 className="mt-4 text-2xl font-black tracking-tight">Fin de semana, sin plan.</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#42645a]">Disfrutad del día libre. El próximo menú os espera el lunes.</p><Link className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-[#1f9e9a] px-4 text-sm font-bold text-white" href="/week">Ver la semana</Link></section> : !items.length ? <section className="mx-5 mt-6 rounded-[1.75rem] bg-[#fff0eb] p-7 sm:mx-7"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#e85d4a]">Organización fácil</p><h2 className="mt-4 text-2xl font-black tracking-tight">Tu semana está por servir.</h2><p className="mt-2 text-sm leading-6 text-[#865044]">Genera el menú y tendrás almuerzo y cena preparados para organizarte.</p><Link className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-[#e85d4a] px-4 text-sm font-bold text-white" href="/week">Generar menú</Link></section> : <section className="space-y-5 px-5 pt-5 sm:px-7">{items.map((item) => {
      const meal = item.meals as { name: string; cooking_method?: string; meal_ingredients?: Ingredient[] }; const lunch = item.meal_slot === "lunch"; const MealIcon = lunch ? Utensils : Moon;
      return <article className={`rounded-[1.75rem] ${lunch ? "bg-[#fff0d8]" : "bg-[#dff4ee]"}`} key={String(item.meal_slot)}><div className="p-6"><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-xs font-black uppercase tracking-wider ${lunch ? "bg-[#f59e42] text-white" : "bg-[#1f9e9a] text-white"}`}>{lunch ? "Almuerzo" : "Cena"}</span><div className="flex items-center gap-3"><MealIcon aria-hidden="true" className="size-5" strokeWidth={2} /><Link aria-label={`Cambiar ${lunch ? "almuerzo" : "cena"}`} className="grid size-10 place-items-center rounded-xl bg-white/75 text-[#66716b]" href={`/change?item=${String(item.id)}&week=${weekStart}`} title={`Cambiar ${lunch ? "almuerzo" : "cena"}`}><RefreshCw aria-hidden="true" className="size-4" strokeWidth={2} /></Link></div></div><h2 className="mt-5 text-2xl font-black leading-tight tracking-tight">{meal.name}</h2>{meal.cooking_method && <p className="mt-2 text-sm font-medium text-[#587065]">{meal.cooking_method}</p>}<div className="mt-6 rounded-2xl bg-white/75 p-4"><p className="text-xs font-black uppercase tracking-wider text-[#66716b]">Para los dos</p><ul className="mt-3 divide-y divide-stone-200/70">{meal.meal_ingredients?.map((ingredient) => <li className="py-3 first:pt-0 last:pb-0" key={ingredient.name}><p className="text-sm font-bold">{ingredient.name}</p>{ingredient.quantity_shared_text ? <p className="mt-1 text-xs text-[#66716b]">Compartido · {ingredient.quantity_shared_text}</p> : <div className="mt-1 grid grid-cols-2 gap-2 text-xs text-[#66716b]"><span>Laura · {quantity(ingredient.quantity_text_laura, ingredient.quantity_laura, ingredient.quantity_note, ingredient.unit, "laura")}</span><span>Jesús · {quantity(ingredient.quantity_text_jesus, ingredient.quantity_jesus, ingredient.quantity_note, ingredient.unit, "jesus")}</span></div>}</li>)}</ul></div></div></article>;
    })}</section>}</main>;
}
