import Link from "next/link";
import { Moon, Utensils } from "lucide-react";
import { notFound } from "next/navigation";
import { ScreenHeader } from "@/components/screen-header";
import { replacementOptions } from "@/domain/menu-generator/generator";
import type { MealCandidate, MenuItem } from "@/domain/menu-generator/types";
import { replaceMeal } from "@/features/weekly-menu/actions";
import { createSupabaseServerClient } from "@/lib/supabase/server";

function candidate(row: Record<string, unknown>): MealCandidate { return { id: String(row.id), name: String(row.name), slot: row.meal_type as MealCandidate["slot"], functionalType: String(row.functional_type), proteinFamily: row.protein_family as MealCandidate["proteinFamily"], active: Boolean(row.active), preference: row.preference_status as MealCandidate["preference"], hasConcentratedCarb: Boolean(row.has_concentrated_carb), isInformal: Boolean(row.is_informal), isBatchCooking: Boolean(row.is_batch_cooking), vegetablesRequired: Boolean(row.vegetables_required) }; }

export default async function ChangePage({ searchParams }: { searchParams: Promise<{ item?: string; week?: string }> }) {
  const { item: itemId, week } = await searchParams; if (!itemId || !week) notFound(); const supabase = await createSupabaseServerClient(); const { data: currentRow } = await supabase.from("weekly_menu_items").select("id, weekly_menu_id, menu_date, meal_slot, meal_id, meals!weekly_menu_items_meal_id_fkey(*)").eq("id", itemId).single(); if (!currentRow) notFound();
  const { data: weekRows } = await supabase.from("weekly_menu_items").select("id, menu_date, meal_slot, meals!weekly_menu_items_meal_id_fkey(*)").eq("weekly_menu_id", currentRow.weekly_menu_id); const { data: library } = await supabase.from("meals").select("*").eq("meal_type", currentRow.meal_slot).eq("active", true).neq("preference_status", "rejected"); const { data: setting } = await supabase.from("app_settings").select("value").eq("key", "alternative_count").maybeSingle();
  const toItem = (row: Record<string, unknown>): MenuItem => ({ day: Math.round((new Date(`${String(row.menu_date)}T12:00:00Z`).getTime() - new Date(`${week}T12:00:00Z`).getTime()) / 86400000), slot: row.meal_slot as MenuItem["slot"], meal: candidate(row.meals as Record<string, unknown>) }); const allItems = (weekRows ?? []).map((row) => toItem(row as Record<string, unknown>)); const current = toItem(currentRow as Record<string, unknown>); const other = allItems.find((entry) => entry.day === current.day && entry.slot !== current.slot); if (!other) notFound(); const configuredLimit = typeof setting?.value === "number" ? setting.value : 4; const alternatives = replacementOptions({ meals: (library ?? []).map((row) => candidate(row as Record<string, unknown>)), recentMealIds: [], settings: { maxDinnerCarbs: 2, varietyMode: "balanced", candidateCount: 1 } }, current, other, allItems, configuredLimit); const lunch = current.slot === "lunch"; const MealIcon = lunch ? Utensils : Moon;
  return <main><ScreenHeader eyebrow="Alternativas compatibles" title={`Cambiar ${lunch ? "almuerzo" : "cena"}`} action={<Link className="rounded-2xl bg-white px-4 py-3 text-sm font-bold shadow-sm" href={`/week?week=${week}`}>Cancelar</Link>} /><section className={`mx-5 mt-4 rounded-2xl p-4 sm:mx-7 ${lunch ? "bg-[#fff4df]" : "bg-[#e9f8f5]"}`}><p className="text-xs font-black uppercase tracking-wider text-[#66716b]">Plato actual</p><p className="mt-1 font-black">{current.meal.name}</p><p className="mt-2 text-xs text-[#66716b]">Las opciones no se repiten en la semana y son compatibles con {other.meal.name}.</p></section><div className="mt-5 space-y-3 px-5 sm:px-7">{alternatives.map((meal) => <article className="rounded-2xl bg-white p-5 shadow-sm" key={meal.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">{meal.name}</h2><p className="mt-1 text-xs font-medium text-[#66716b]">Compatible con el otro plato del día</p></div><MealIcon aria-hidden="true" className="size-5" strokeWidth={2} /></div><form action={replaceMeal} className="mt-5"><input name="itemId" type="hidden" value={itemId}/><input name="mealId" type="hidden" value={meal.id}/><input name="week" type="hidden" value={week}/><button className={`min-h-11 w-full rounded-xl font-black text-white ${lunch ? "bg-[#f59e42]" : "bg-[#1f9e9a]"}`}>Elegir este plato</button></form></article>)}{!alternatives.length && <p className="rounded-2xl bg-white p-5 text-sm text-[#66716b] shadow-sm">No hay alternativas sin repetir para esta semana. Cambia el menú completo o activa más platos en la biblioteca.</p>}</div></main>;
}
