import Link from "next/link";
import { ChevronLeft, ChevronRight, Moon, Utensils } from "lucide-react";
import { ScreenHeader } from "@/components/screen-header";
import { generateWeek } from "@/features/weekly-menu/actions";
import { createSupabaseServerClient } from "@/lib/supabase/server";

function currentMonday() { const now = new Date(); now.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return now.toISOString().slice(0, 10); }
function shiftMonday(start: string, weeks: number) { const date = new Date(`${start}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + weeks * 7); return date.toISOString().slice(0, 10); }

export default async function WeekPage({ searchParams }: { searchParams: Promise<{ week?: string }> }) {
  const weekStart = (await searchParams).week ?? currentMonday(); const supabase = await createSupabaseServerClient(); const { data: menu, error: menuError } = await supabase.from("weekly_menus").select("id").eq("week_start", weekStart).maybeSingle();
  const { data: menuItems, error: itemsError } = menu ? await supabase.from("weekly_menu_items").select("id, menu_date, meal_slot, was_replaced, meals!weekly_menu_items_meal_id_fkey(name)").eq("weekly_menu_id", menu.id) : { data: [], error: null };
  const items = (menuItems ?? []) as Array<Record<string, unknown>>; const dates = Array.from({ length: 5 }, (_, index) => { const date = new Date(`${weekStart}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + index); return date; }); const range = `${dates[0]!.toLocaleDateString("es-ES", { day: "numeric", month: "short" })} - ${dates[4]!.toLocaleDateString("es-ES", { day: "numeric", month: "short" })}`; const error = menuError ?? itemsError;
  return <main><ScreenHeader eyebrow="Planifica con calma" title="Tu semana" action={<Link className="rounded-2xl bg-white px-4 py-3 text-sm font-bold shadow-sm" href={`/week?week=${currentMonday()}`}>Hoy</Link>} /><div className="mx-5 mt-3 flex items-center justify-between rounded-2xl bg-white p-2 shadow-sm sm:mx-7"><Link aria-label="Semana anterior" className="grid size-11 place-items-center rounded-xl bg-[#fff8f0]" href={`/week?week=${shiftMonday(weekStart, -1)}`}><ChevronLeft aria-hidden="true" className="size-5" strokeWidth={2} /></Link><p className="text-sm font-black capitalize text-[#24302b]">{range}</p><Link aria-label="Semana siguiente" className="grid size-11 place-items-center rounded-xl bg-[#fff8f0]" href={`/week?week=${shiftMonday(weekStart, 1)}`}><ChevronRight aria-hidden="true" className="size-5" strokeWidth={2} /></Link></div>
    {error ? <section className="mx-5 mt-6 rounded-3xl bg-[#fff0eb] p-6 text-[#8e3c2f] sm:mx-7"><h2 className="font-black">No se pudo cargar esta semana</h2><p className="mt-2 text-sm">{error.message}</p></section> : !menu ? <section className="mx-5 mt-6 rounded-[1.75rem] bg-[#24302b] p-7 text-white sm:mx-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#91c95a]">Todo listo</p><h2 className="mt-3 text-2xl font-black tracking-tight">Diseña tus 10 comidas.</h2><p className="mt-2 text-sm leading-6 text-stone-300">Cinco almuerzos y cinco cenas, con variedad y cantidades guardadas.</p><form action={generateWeek} className="mt-6"><input name="weekStart" type="hidden" value={weekStart}/><button className="min-h-12 rounded-xl bg-[#91c95a] px-5 text-sm font-black text-[#24302b]">Generar semana</button></form></section> : <><form action={generateWeek} className="mx-5 mt-6 sm:mx-7"><input name="weekStart" type="hidden" value={weekStart}/><input name="replace" type="hidden" value="true"/><button className="min-h-11 rounded-xl border border-[#e85d4a] px-4 text-sm font-bold text-[#e85d4a]">Regenerar semana</button></form><section className="mt-5 space-y-4 px-5 sm:px-7">{dates.map((date) => { const dateKey = date.toISOString().slice(0, 10); return <article className="rounded-[1.5rem] bg-white p-5 shadow-sm" key={dateKey}><div className="flex items-center justify-between"><h2 className="text-base font-black capitalize">{date.toLocaleDateString("es-ES", { weekday: "long" })}</h2><span className="rounded-full bg-[#fff8f0] px-3 py-1 text-xs font-bold text-[#66716b]">{date.toLocaleDateString("es-ES", { day: "numeric", month: "short" })}</span></div><div className="mt-4 grid gap-2">{(["lunch", "dinner"] as const).map((slot) => { const item = items.find((value) => value.menu_date === dateKey && value.meal_slot === slot); const meal = item?.meals as { name?: string } | undefined; const lunch = slot === "lunch"; const MealIcon = lunch ? Utensils : Moon; return <div className={`flex items-center gap-3 rounded-2xl p-3 ${lunch ? "bg-[#fff4df]" : "bg-[#e9f8f5]"}`} key={slot}><MealIcon aria-hidden="true" className="size-5" strokeWidth={2} /><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-wider text-[#66716b]">{lunch ? "Almuerzo" : "Cena"}</p><p className="truncate text-sm font-bold">{meal?.name ?? "Sin asignar"}</p></div>{item && <Link aria-label={`Cambiar ${lunch ? "almuerzo" : "cena"}`} className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#24302b]" href={`/change?item=${String(item.id)}&week=${weekStart}`}>Cambiar</Link>}</div>; })}</div></article>; })}</section><p className="mx-5 mt-5 text-center text-xs font-bold text-[#66716b] sm:mx-7">Sábado y domingo son días libres.</p></>}</main>;
}
